<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-3M4V40Q9" ignored="0" name="SignUp Validation" tests="11" failures="1" timestamp="29 Dec 2020 15:34:13 GMT" time="167.365" errors="0">
  <testcase name="verifySignUp" time="3.959" classname="TestCases.signUpValidation"/>
  <testcase name="verifySignUp" time="6.003" classname="TestCases.signUpValidation">
    <failure type="java.lang.AssertionError" message="expected [false] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [1]
at Pages.Register.Signup(Register.java:40)
at TestCases.signUpValidation.verifySignUp(signUpValidation.java:59)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- verifySignUp -->
  <testcase name="verifySignUp" time="5.226" classname="TestCases.signUpValidation"/>
  <testcase name="verifySignUp" time="5.372" classname="TestCases.signUpValidation"/>
  <testcase name="verifySignUp" time="5.647" classname="TestCases.signUpValidation"/>
  <testcase name="verifySignUp" time="4.445" classname="TestCases.signUpValidation"/>
  <testcase name="verifySignUp" time="6.273" classname="TestCases.signUpValidation"/>
  <testcase name="verifySignUp" time="6.099" classname="TestCases.signUpValidation"/>
  <testcase name="verifySignUp" time="8.533" classname="TestCases.signUpValidation"/>
  <testcase name="verifySignUp" time="6.468" classname="TestCases.signUpValidation"/>
  <testcase name="verifySignUp" time="6.306" classname="TestCases.signUpValidation"/>
</testsuite> <!-- SignUp Validation -->
