<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-3M4V40Q9" name="TestCases.RegisterValidation" tests="11" failures="1" timestamp="29 Dec 2020 14:58:43 GMT" time="242.546" errors="0">
  <testcase name="verifySignUp" time="25.705" classname="TestCases.RegisterValidation"/>
  <testcase name="verifySignUp" time="22.088" classname="TestCases.RegisterValidation"/>
  <testcase name="verifySignUp" time="17.169" classname="TestCases.RegisterValidation"/>
  <testcase name="verifySignUp" time="17.942" classname="TestCases.RegisterValidation"/>
  <testcase name="verifySignUp" time="31.543" classname="TestCases.RegisterValidation"/>
  <testcase name="verifySignUp" time="21.833" classname="TestCases.RegisterValidation"/>
  <testcase name="verifySignUp" time="16.108" classname="TestCases.RegisterValidation"/>
  <testcase name="verifySignUp" time="31.423" classname="TestCases.RegisterValidation"/>
  <testcase name="verifySignUp" time="20.866" classname="TestCases.RegisterValidation"/>
  <testcase name="verifySignUp" time="14.487" classname="TestCases.RegisterValidation">
    <failure type="java.lang.AssertionError" message="expected [false] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [1]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:442)
at Pages.Register.Signup(Register.java:36)
at TestCases.RegisterValidation.verifySignUp(RegisterValidation.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifySignUp -->
  <testcase name="verifySignUp" time="23.382" classname="TestCases.RegisterValidation"/>
</testsuite> <!-- TestCases.RegisterValidation -->
